### ISSUE TITLE
Doc should be clear that BluePrint only creates new components, doesn't support updates

### ISSUE THREAD

**Issue by cilex-ft** [laravel-shift/blueprint-docs#10]
I've just started using BluePrint and after reading the doc, ["it's common to simply reuse the draft.yaml file over and over again to continue to generate code for your application"](https://blueprint.laravelshift.com/docs/generating-components/), I was (wrongly) under the impression that I just could define a column and have my model updated.

I had to read many issues to finally find [this one](https://github.com/laravel-shift/blueprint/issues/3).

I probably shouldn't believe in magic anymore, but I can't help...

I think the doc should make clear that models can't be updated, and/or give any clues to bypass this.

**Comment by jasonmccreary** [comment]
How about:

> While you are welcome to create separate draft files, it's common to simply reuse the `draft.yaml` file over and over again to generate code for your application.

**Comment by jasonmccreary** [comment]
Updated in b68b094
