### ISSUE TITLE
New Addon

### ISSUE THREAD

**Issue by tanthammar** [laravel-shift/blueprint-docs#11]
I've created a Blueprint addon for TALL-forms.
Would you consider adding it to the list of integrations?

https://github.com/tanthammar/tall-blueprint-addon

Example
[**TALL-forms**:](https://github.com/tanthammar/tall-blueprint-addon) Automatically generate forms for each of the models specified in your draft file.

**Comment by jasonmccreary** [comment]
Done in 7701cdf72
