### ISSUE TITLE
Invokable controllers

### ISSUE THREAD

**Issue by jakub-wolowski** [laravel-shift/blueprint-docs#13]
As the creation of [invokable controllers](https://github.com/laravel-shift/blueprint/pull/435) got released, I'd also like to add it to the docs. I think it would best fit into the [controller shorthands section](https://blueprint.laravelshift.com/docs/controller-shorthands/)?

**Comment by jasonmccreary** [comment]
Yeah, that'd be great. Maybe mention it at the top and page link to a section at the bottom?

**Comment by jasonmccreary** [comment]
Closed by #14
