### ISSUE TITLE
Enhance doc regarding generator UI: drawsql.app

### ISSUE THREAD

**Issue by pikant** [laravel-shift/blueprint-docs#16]
After some searching for a UI to generate Laravel Blueprint `draft.yaml` files, I accidentally found out that https://drawsql.app can also generate Blueprint files.

It would be nice to mention this in the documentation.

**Comment by jasonmccreary** [comment]
I have added a new "Additional Services" section to the [Extending Blueprint](https://blueprint.laravelshift.com/docs/extending-blueprint/) page.
