### ISSUE TITLE
Blueprint how can we ignore existing models?

### ISSUE THREAD

**Issue by adam-code-labx** [laravel-shift/blueprint-docs#30]
Just starting a new project and blueprint is great.
I was able to setup the initial structure of my app within minutes 🔥

One question is how do I append additional models without overriding everything?
I assumed running `blueprint:trace` would cache the models generated so that running again with the additional models appended to draft.yaml would only generate the new model.

However it seems to override everything which is not ideal after editing each model.
Expected behaviour would be to ignore anything which is already in `.blueprint` then just add new model Bid for example.

```cmd
models:
    Auction: {  }
    Buyer: {  }
    Category: {  }
    Item: {  }
    Price: {  }
    Seller: {  }
    User: { }
    UserProfile: {  }
```

Current workaround is to comment out the generated models in draft.yaml
Certainly not ideal hoping there is a better way? or perhaps I can create a PR at some point to ignore anything with has been previously generated by the build command?

Additionally are you planning support enum generation?
for example it would be useful to generate Enums based from the field.
`buyer_status: enum:pending,paid,reviewed,refunded,cancelled,disputed,completed`

**Comment by jasonmccreary** [comment]
The _draft file_ is not cumulative. It's more of a scratch pad where you generate fresh ideas.
