### ISSUE TITLE
Best way to extends model lexers

### ISSUE THREAD

**Issue by thewebartisan7** [laravel-shift/blueprint-docs#31]
I have a questions about extending blueprint, since the docs doesn't cover too much about it, and I have not a twitter account to ask there, so sorry to jump here with this question.

I create a custom generator which starting from a model defined in draft.yaml, generate the controllers and basic views with a table with sorting and filtering.

All works fine so far, pretty powerful package!

At the moment I have just get all columns from model using `$model->columns()` and making all string, number and dates sortable and filterable.

I would like to add some new info inside draft.yaml when defining the model.

Somethiing like:

```
models:
  Post:
    title: string:255 sortable filterable
    content: longtext filterable
    published_at: nullable timestamp
    softDeletes

seeders: Post
```

I think such things should be done in the lexer, since we can only overrides the generators via config, is there a way to do this without creating custom model generator and model lexer?

Thanks

**Comment by jasonmccreary** [comment]
Yes, adding new tokens to the grammar would need to be parsed in the Lexer and then stored in the underlying data class. In this case, the `ModelLexer` would parse `sortable` and `filterable` and assign them to properties inside the `Model` class.

I will say, the combination of the two might be a bit difficult. Currently there isn't a way to swap out a Lexer or data class. You can add a Lexer calling `registerLexer()`. But that still leaves the data class.

Without knowing the goal of `sortable` and `filterable`, it's hard to suggest an approach. Options might be:

- Write a separate Lexer and data class to extract the information you need and then a Generator to output. This would only work if you are generating your own files/code.
- Similar to the above, but overwrite the existing Generator to change the output of the files/code Blueprint already generators.
- Fork Blueprint to add these core tokens and use your own fork.

**Comment by thewebartisan7** [comment]
Thanks for your input, I much appreciate.

The `filterable` and `sortable` will be added in the controller method, passed to a spatie query builder wrapper, current stub is:

```php
    public function index(QueryBuilder $queryBuilder, {{ modelClass }} ${{ modelVariable }}): Response
    {
        $builder = $queryBuilder
            ->for(${{ modelVariable }})
            ->withColumns(
                collect([
                    {{ columns }}
                ]))
            ->withFilterByKey('{{ primaryKey }}')
            ->build();

        return Inertia::render('Admin/{{ modelClass }}/{{ modelClass }}List', [
            'queryBuilder' => $builder->paginate(),
            'columns' => $builder->getColumns()
        ]);
    }
 ```
{{ columns }} will be replaced by an array like:

```php
[
 ['name' => 'id', 'header' => 'Id', 'sortable' => true, 'filterable' => false],
 // ...
]
```

Forking might not be a solution, as I would like to make a package, and I think there are some solutions as you mention. I think of this and some others but before start I want to see if I missed something. Currently the only way is to learn from code, it's pitty there are not some more docs about it. 

After watching your video on how you write seeders generator, I might do something similar, so the draft.yaml for Model will be the same as is now, and then add a new type for add more tokens, something like:

models:
  Post:
    title: string:255 sortable filterable
    content: longtext filterable
    published_at: nullable timestamp
    softDeletes

seeders: Post

```
tables:
  Post:
    title: sortable filterable
    content: filterable
    published_at: true
```

so that title is sortable and filterable, content is filterable, and publish_at is just display with no sort or filter.

I think this way I can still keep the same logic of looping over models and then retrieve the `tables` informations by matching the model name... Not yet sure how would that works, current output method is something like below:

```php
public function output(Tree $tree): array
    {
        $this->tree = $tree;
        $stub = $this->filesystem->stub('controller.class.stub');

        foreach ($tree->models() as $model) {
            $this->addImport($model, 'App\\Http\\Controllers\\Controller');
            $this->addImport($model, 'Inertia\\Inertia');
           // ... more imports

            // Create base form request
            $path = Blueprint::appPath() . '/Http/Requests/Admin/' . $model->name() . '/' . $model->name() . 'Request.php';
            $this->create($path, $this->populateRequestStub($model));

            // Create controller
            $path = Blueprint::appPath() . '/Http/Controllers/Admin/' . $model->name() . '/' . $model->name() . 'TableController.php';
            $this->create($path, $this->populateStub($stub, $model));

            // Add routes
            // ...

            // Create inertia page
            $path = 'resources/js/Pages/Admin/' . Str::pluralStudly($model->name()) . '/' . $model->name() . 'List.tsx';
            $this->create($path, $this->buildInertiaPage($model));
            $this->output['created'][] = $path;
        }

        return $this->output;
    }
```

I hope I can ask you more questions here about this. 

Thank You!

**Comment by thewebartisan7** [comment]
Works great with a custom lexer and generator! Thanks !

Custom lexer:

```php
<?php
namespace App\Support;

use Blueprint\Contracts\Lexer;

class TableLexer implements Lexer
{
    public function analyze(array $tokens): array
    {
        $registry = ['table' => []];

        if (!empty($tokens['table'])) {
            foreach ($tokens['table'] as $modelName => $columns) {
                $registry['table'][$modelName] = $this->analyzeColumns($columns);
            }
        }

        return $registry;
    }

    private function analyzeColumns(array $columns): array
    {
        $tokens = [];

        foreach ($columns as $column => $definitions) {
            $definitions = preg_split('/\s+/', $definitions);

            $token = [];
            foreach ($definitions as $definition) {
                $definition = explode(':', $definition);

                $token[$definition[0]] = $definition[1] ?? true;
            }

            $token['header'] = ucfirst(str_replace('_', ' ', $column));

            $tokens[$column] = $token;
        }

        return $tokens;
    }
}
```

Current generator output:

```php
    public function output(Tree $tree): array
    {
        $this->tree = $tree;

        foreach ($this->tree->toArray()['table'] as $model => $definitions) {
            $model = new Model($model);
       
           // $definitions contains all extra info I need for each columns

        }

        return $this->output;
    }
```

I can't see other way to retrieve the tokens from tree but to convert the tree to an array. Not a big problem, but maybe there is other way.
