### ISSUE TITLE
Controllers: MyController: resource: all doesn't work as documented

### ISSUE THREAD

**Issue by incredimike** [laravel-shift/blueprint-docs#8]
In your docs you suggest that `all`, `api`, and `web` are valid resource options. See 6 paragraphs down on page  https://blueprint.laravelshift.com/docs/controller-shorthands/ 

Reviewing RouteGenerator.php, I see that `all` is not a valid option.
https://github.com/laravel-shift/blueprint/blob/7c9a32ef8e46796c2ef18a21f6bbb2359690fc3c/src/Generators/RouteGenerator.php#L20

In testing, using `all` generates an empty controller.

**Comment by jasonmccreary** [comment]
This was indeed removed a while back as `all` never really made much sense.

I have corrected and published the docs.
